# Exercise 4: Hierarchical Indexing in pandas

In [1]:
import pandas as pd
import numpy as np

This set of exercises focuses on hierarchical indexing.  First, let's create some data that includes data for three individuals ('A', 'B', 'C') across several years:

In [33]:
data_list = [ [1977, 'A', 1.20, 0.60], 
        [1977, 'B', 1.50, 0.50], 
        [1977, 'C', 1.70, 0.80],
        [1978, 'A', 0.20, 0.06],
        [1978, 'B', 0.70, 0.20],
        [1978, 'C', 0.80, 0.30],
        [1978, 'D', 0.90, 0.50],
        [1978, 'E', 1.40, 0.90],
        [1979, 'C', 0.20, 0.15],
        [1979, 'D', 0.14, 0.05],
        [1979, 'E', 0.50, 0.15],
        [1979, 'F', 1.20, 0.50],
        [1979, 'G', 3.40, 1.90],
        [1979, 'H', 5.40, 2.70],
        [1979, 'I', 6.40, 1.20] ]
data = pd.DataFrame(data_list, columns=['year', 'indiv', 'x', 'z'])
data

    year indiv     x     z
0   1977     A  1.20  0.60
1   1977     B  1.50  0.50
2   1977     C  1.70  0.80
3   1978     A  0.20  0.06
4   1978     B  0.70  0.20
5   1978     C  0.80  0.30
6   1978     D  0.90  0.50
7   1978     E  1.40  0.90
8   1979     C  0.20  0.15
9   1979     D  0.14  0.05
10  1979     E  0.50  0.15
11  1979     F  1.20  0.50
12  1979     G  3.40  1.90
13  1979     H  5.40  2.70
14  1979     I  6.40  1.20

Using this data answer the following questions:

* Create a hierarchical index for the DataFrame based on the ``year`` and ``indiv`` columns using the [set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) method.

In [34]:
data = data.set_index(['year', 'indiv'])
data

               x     z
year indiv
1977 A      1.20  0.60
     B      1.50  0.50
     C      1.70  0.80
1978 A      0.20  0.06
     B      0.70  0.20
     C      0.80  0.30
     D      0.90  0.50
     E      1.40  0.90
1979 C      0.20  0.15
     D      0.14  0.05
     E      0.50  0.15
     F      1.20  0.50
     G      3.40  1.90
     H      5.40  2.70
     I      6.40  1.20

* Extract the data from 1977

In [35]:
# the 1977 data
index = pd.IndexSlice
data.loc[index[1977, :], :]

              x    z
year indiv
1977 A      1.2  0.6
     B      1.5  0.5
     C      1.7  0.8

* Extract the data for individual A

In [37]:
# the data for individual A
# keep in mind that the following won't work:
# data.loc[:, 'A']
# use pd.IndexSlice or reorder the levels of the index using the pandas 
# swaplevel method
data.loc[index[:, 'A'], :]

              x     z
year indiv
1977 A      1.2  0.60
1978 A      0.2  0.06

* When performing `data.unstack()` on your multi-indexed DataFrame you get a lot of `Nan`s.  Explain why!

In [38]:
# data.unstack()
data.unstack()

         x                                              z                   \
indiv    A    B    C     D    E    F    G    H    I     A    B     C     D
year
1977   1.2  1.5  1.7   NaN  NaN  NaN  NaN  NaN  NaN  0.60  0.5  0.80   NaN
1978   0.2  0.7  0.8  0.90  1.4  NaN  NaN  NaN  NaN  0.06  0.2  0.30  0.50
1979   NaN  NaN  0.2  0.14  0.5  1.2  3.4  5.4  6.4   NaN  NaN  0.15  0.05


indiv     E    F    G    H    I
year
1977    NaN  NaN  NaN  NaN  NaN
1978   0.90  NaN  NaN  NaN  NaN
1979   0.15  0.5  1.9  2.7  1.2

The reason why the multi-indexed DataFrame gets a lot of NaN is due to the fact that there is more data for certain years with 1979 having C-I for indiv, 1977 having only A-C, and 1978 having A-E. Since unstack method has to retain the overall strucuture of the data it has to incorporate A-I for all years as this is the range for all years combined. This then creates these NaN's as (1977,F) never occured so therefore it recieves a NaN.

* Run the statement `data['z'] == data.loc[:,'z']` and explain the result.

In [39]:
data['z'] == data.loc[:,'z']

year  indiv
1977  A        True
      B        True
      C        True
1978  A        True
      B        True
      C        True
      D        True
      E        True
1979  C        True
      D        True
      E        True
      F        True
      G        True
      H        True
      I        True
Name: z, dtype: bool

As we can see the result is True for all years and indiv, this is because for data.loc[:,
'z'] it is practically going through all the rows and selecting the values in column z and comparing these values with a boolean argument of data['z'] which is also selecting the values in the z column. These statements are practically identical on both sides of the boolean equallity sign, therefore the results are True for all the comparisons of row 'z'.

* Add a new column to the data called `Mean` which equals the average of the two columns.  Use the `mean` method of a pandas DataFrame.

In [40]:
# add a mean column
data['mean'] = data.mean(axis = 1)
data

               x     z   mean
year indiv
1977 A      1.20  0.60  0.900
     B      1.50  0.50  1.000
     C      1.70  0.80  1.250
1978 A      0.20  0.06  0.130
     B      0.70  0.20  0.450
     C      0.80  0.30  0.550
     D      0.90  0.50  0.700
     E      1.40  0.90  1.150
1979 C      0.20  0.15  0.175
     D      0.14  0.05  0.095
     E      0.50  0.15  0.325
     F      1.20  0.50  0.850
     G      3.40  1.90  2.650
     H      5.40  2.70  4.050
     I      6.40  1.20  3.800